name: commit

on:
  watch:
    types: [started]
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - id: star
      run: |
        python main.py ${{ secrets.PAT }} $GITHUB_REPOSITORY
        echo "::set-output name=name::$(awk -f '{print $1}' /tmp/user.txt)"
        echo "::set-output name=count::$(awk -f '{print $2}' /tmp/user.txt)"
    - run: |
        echo ${{ steps.star.outputs.email }} ${{ steps.star.outputs.name }} ${{ steps.star.outputs.count }}
        git config --local user.email "${{ github.actor }}@users.noreply.github.com"
        git config --local user.name "${{ github.actor }}"
        git add .
        git commit -m "${{ steps.star.outputs.count }} 🌟" -a
        git push
